package projecteuler.problem2

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
fun main(args: Array<String>) {
    var result = 0
    val fibonacciNumbers = mutableListOf(0, 1)
    for (i in 2 until 4000000) {
        fibonacciNumbers.add(fibonacciNumbers[i - 1] + fibonacciNumbers[i - 2])
    }
    for (fibNo in fibonacciNumbers) {
        if (fibNo % 2 == 0) {
            result += fibNo
        }
    }
    print("The sum of all even fibonacci-terms is $result")
}